# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b82b2463cb8a53381ad38f6fb3c9c035c7f54e5ff816130c94dd864b109e00ebc05b766767d3db70d32e75ad8a6c401d66164b0cde5d2972a3bb26f2cb4a00b8

test:
  secret_key_base: 8cfd45fc12b68f0030f828e0831f235ec338c61d66b039db9fcb88b79848dbca4c7d48965767c505aebcf9d7f022e576509ef736387c4141d5fa1f68311dbc12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
